# -*- coding: utf-8 -*-
"""ANLP3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mFt2B_OUUSCXXwK7_NPkbbvuPmfOy96u
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/UKPLab/iclr2025-psa.git
# %cd iclr2025-psa

!pip install -r requirements.txt
!pip install steering-vectors torchaudio matplotlib

# Commented out IPython magic to ensure Python compatibility.
# %cd iclr2025_psa
# %ls

from huggingface_hub import login
login()

import os

os.makedirs("results", exist_ok=True)
print("Created 'results/' folder:", os.listdir("results"))

!PYTHONPATH=. python run.py \
--model "google/gemma-2b-it" \
--dataset "sycophancy" \
--layers 11 12 13 14 15 \
--noise_multiplier 0.02

!PYTHONPATH=. python run.py \
--model "google/gemma-2b-it" \
--dataset "hallucination" \
--layers 11 12 13 14 15 \
--noise_multiplier 0.02

!PYTHONPATH=. python run.py \
--model "google/gemma-2b-it" \
--dataset "refusal" \
--layers 11 12 13 14 15 \
--noise_multiplier 0.02

!PYTHONPATH=. python run.py \
--model "google/gemma-2b-it" \
--dataset "myopic-reward" \
--layers 11 12 13 14 15 \
--noise_multiplier 0.02

!PYTHONPATH=. python run.py \
--model "google/gemma-2b-it" \
--dataset "survival-instinct" \
--layers 11 12 13 14 15 \
--noise_multiplier 0.02

!PYTHONPATH=. python run.py \
--model "google/gemma-2b-it" \
--dataset "coordinate-other-ais" \
--layers 11 12 13 14 15 \
--noise_multiplier 0.02

!PYTHONPATH=. python run.py \
--model "google/gemma-2b-it" \
--dataset "corrigible-neutral-HHH" \
--layers 11 12 13 14 15 \
--noise_multiplier 0.02

!PYTHONPATH=. python run.py \
--model "Qwen/Qwen2.5-7B-Instruct" \
--dataset "corrigible-neutral-HHH" \
--layers 20 21 22 23 24 \
--noise_multiplier 0.02

!PYTHONPATH=. python run.py \
--model "Qwen/Qwen2.5-7B-Instruct" \
--dataset "coordinate-other-ais" \
--layers 20 21 22 23 24 \
--noise_multiplier 0.02